language: node_js
node_js:
  - 10
jobs:
  include:
    - stage: deploy-npm
      env: Type='NPM Deploy'
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          all_branches: true
          repo: whamcloud/help
stages:
  - name: deploy-npm
    if: branch =~ ^v\d+\.\d+\.\d+$
