language: node_js
node_js:
  - 6
before_install:
  - npm i -g npm@latest
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
env:
  secure: P9cUIbyZZ7DmKfwnKmiMNw5SluTQ1rH9w7EvwkTqGuZBBhRzNdtkaJvne5A+bLuE5DQht0HzKuiUhVjH2k6NstAK6BfYh3P4gbWQxLFbsccvVeJybZ9et3JtAqJATlHJdTww9Vhh2hU+P0zBHgBnkfnUotsaaVzkF2p44d3Mgjp1Tmd50iSHPa9FRMwdHqCBmTGc3pyk/vmXqj4UEPdriLArkNBwE3FHd5BcccF1AOpBo6yzr0RgaThvm3xbWam5CbEoYzrrh7HBjwsVcX8NF7kyMj4c4iffHSsinE90KaaDvo58pgc21BXRrU/Y68GcdJaVvHcSFrbOv2FlKWdIO/QTIabN9ScVaZbEIYsAiptLFdotOd8ZCCRLvmJRCE4swaTzbJpGEP7TOYg6vUVZd5um0uuKY6ny0GO0GEspEeWZbC5o7TLWb/YsGvs0ZrejA1dZOTYfVHW2d2ZX3bLTxHXctlBFXqt7pjLCr55F+ULa/EvMQCugAGIcrL9wn63tXm8kzXVr98M05rraQOnV50giDWBjNpeB7fqjh6MadlmFfXEa8usigJMNRhQg3Tu/nhff3a/VS47cZ1lbB0Abd9o2CURVSFyGRJ2UkJzRvZWeBjPr5gu6voEtOnmJXzuGfyCtZqbtpwDoQUYYYqwozPnPca3SBT2vXfOQP0sDooY=
deploy:
  provider: npm
  api_key:
    secure: P9cUIbyZZ7DmKfwnKmiMNw5SluTQ1rH9w7EvwkTqGuZBBhRzNdtkaJvne5A+bLuE5DQht0HzKuiUhVjH2k6NstAK6BfYh3P4gbWQxLFbsccvVeJybZ9et3JtAqJATlHJdTww9Vhh2hU+P0zBHgBnkfnUotsaaVzkF2p44d3Mgjp1Tmd50iSHPa9FRMwdHqCBmTGc3pyk/vmXqj4UEPdriLArkNBwE3FHd5BcccF1AOpBo6yzr0RgaThvm3xbWam5CbEoYzrrh7HBjwsVcX8NF7kyMj4c4iffHSsinE90KaaDvo58pgc21BXRrU/Y68GcdJaVvHcSFrbOv2FlKWdIO/QTIabN9ScVaZbEIYsAiptLFdotOd8ZCCRLvmJRCE4swaTzbJpGEP7TOYg6vUVZd5um0uuKY6ny0GO0GEspEeWZbC5o7TLWb/YsGvs0ZrejA1dZOTYfVHW2d2ZX3bLTxHXctlBFXqt7pjLCr55F+ULa/EvMQCugAGIcrL9wn63tXm8kzXVr98M05rraQOnV50giDWBjNpeB7fqjh6MadlmFfXEa8usigJMNRhQg3Tu/nhff3a/VS47cZ1lbB0Abd9o2CURVSFyGRJ2UkJzRvZWeBjPr5gu6voEtOnmJXzuGfyCtZqbtpwDoQUYYYqwozPnPca3SBT2vXfOQP0sDooY=
  on:
    tags: true
    repo: intel-hpdd/help
    branch: master
