language: node_js
node_js:
- 6
before_install:
- npm i -g npm@latest
- npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
env:
  secure: P9cUIbyZZ7DmKfwnKmiMNw5SluTQ1rH9w7EvwkTqGuZBBhRzNdtkaJvne5A+bLuE5DQht0HzKuiUhVjH2k6NstAK6BfYh3P4gbWQxLFbsccvVeJybZ9et3JtAqJATlHJdTww9Vhh2hU+P0zBHgBnkfnUotsaaVzkF2p44d3Mgjp1Tmd50iSHPa9FRMwdHqCBmTGc3pyk/vmXqj4UEPdriLArkNBwE3FHd5BcccF1AOpBo6yzr0RgaThvm3xbWam5CbEoYzrrh7HBjwsVcX8NF7kyMj4c4iffHSsinE90KaaDvo58pgc21BXRrU/Y68GcdJaVvHcSFrbOv2FlKWdIO/QTIabN9ScVaZbEIYsAiptLFdotOd8ZCCRLvmJRCE4swaTzbJpGEP7TOYg6vUVZd5um0uuKY6ny0GO0GEspEeWZbC5o7TLWb/YsGvs0ZrejA1dZOTYfVHW2d2ZX3bLTxHXctlBFXqt7pjLCr55F+ULa/EvMQCugAGIcrL9wn63tXm8kzXVr98M05rraQOnV50giDWBjNpeB7fqjh6MadlmFfXEa8usigJMNRhQg3Tu/nhff3a/VS47cZ1lbB0Abd9o2CURVSFyGRJ2UkJzRvZWeBjPr5gu6voEtOnmJXzuGfyCtZqbtpwDoQUYYYqwozPnPca3SBT2vXfOQP0sDooY=
deploy:
  provider: npm
  email: joe.grund@intel.com
  api_key:
    secure: JumdUzL9ge6BjWSWQpbhu6AsZzZizcnktSQlxprVHic0z5c7O0S+IZHUrasOa+rzXeePe7uTT21EkPDuWJXiH+A1s4tjIAVrNV7DquYzFAzKnMLooXj0Gx9y361CGsV0HzfvutPDrxc3aIGO+6My+ND1gtMkhDoIkjoarsk/vSwLsXIiCMNk0jl/cFWcpByCSrnTHeH2m/oWiiwVXG9FW/Lrkf/jKKmMYLJS28qMi8cnMvRow/JiuXb6vrMhxSQ4YMXspc93+X4Pc5/Dgp92WsYeh9UEGoU9454sPDavV6nVNWrXdfvZzroY9TtmHMTR2+O9VvIypFOGuKx38L3iVqwKszIyMxlpNAI7wHMW0WcRqj7kWbw/45F0pQKvUJX8psrAWehj+y0LP6OnU2AfhkOaIUaEP6R3qW4bDC/BBf1zDvA11I7gde1JYY/P3fiLZz8lWKnM3yFO1r+RO8FCFQIFvMHbOm4WplIaU0lIeshrRLI5y0cPdaqi+1JG1rxDgWd9fQaHmmh6Ja+XzO+maWkdgu9+LjLMpeom0ZkWgSE2KOJ2KU8UD+Qsx9oTr4jZNhxjZ16XDwit0HAoAQT2ALHq5UgqP7EaKHTag6LjcGCxc5QcDqvYbp01fjqauZP+CIm/fmzr0CIjOMZsmPpS2cxFDwByR8f8QdoEsE3NhlU=
  on:
    tags: true
    repo: intel-hpdd/help
    branch: master
